docker image test

diff --git a/LLM/MCP/1-hello-world/Dockerfile b/LLM/MCP/1-hello-world/Dockerfile
--- a/LLM/MCP/1-hello-world/Dockerfile
+++ b/LLM/MCP/1-hello-world/Dockerfile
@@ -16,15 +16,15 @@ ENV UV_NO_DEV=1
 WORKDIR /app
 RUN uv lock && uv sync --frozen && uv pip install -e ".[dev]" 
 
-# RUN tests
-RUN uv run pytest tests/maintests.py -v
+# # RUN tests
+# RUN uv run pytest tests/maintests.py -v
 
 # Expose the port
 EXPOSE 8000
 
-# Health check
-HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
-    CMD python -c "import requests; requests.get('http://localhost:8000/health')" || exit 1
+# # Health check
+# HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
+#     CMD python -c "import requests; requests.get('http://localhost:8000/health')" || exit 1
 
 # Run the application
 # uv run src/main.py
